services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pm-client
    container_name: pm-client
    depends_on:
      - server
    ports:
      - "5173:5173"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: pm-server
    container_name: pm-server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - node_modules_rentra:/app/node_modules
    environment:
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GMAIL_APP_PASSWORD
      - GMAIL_USER
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - PORT
      - SUPABASE_API_KEY
      - SUPABASE_CONNECTION_STRING
      - SUPABASE_POSTGRES_PASSWORD
      - SUPABASE_SERVICE_ROLE_KEY
      - SUPABASE_PUBLIC_BUCKET_NAME
      - SUPABASE_PRIVATE_BUCKET_NAME
      - SUPABASE_URL
volumes:
  node_modules_rentra:
